export const CONSTANTS = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SHIPPMENT_SCREEN: 'SHIPMENT_SCREEN',
  SCAN_SCREEN: 'SCAN_SCREEN',
  WALLET_SCREEN: 'WALLET_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  LOGIN_SCREEN_FORM: 'LOGIN_SCREEN_FORM',
  AUTH: 'AUTH',
  APP: 'APP',
};
