export interface IShipmentData {
  name: string;
  creation: string;
  modified: string;
  modified_by: string;
  owner: string;
  docstatus: number;
  idx: number;
  sender: string;
  origin_area: null | string;
  origin_city: string;
  sender_phone: string;
  sender_name: string;
  origin_adress_line_1: null | string;
  origin_country: string;
  sender_address: null | string;
  origin_address_line2: null | string;
  origin_state: string;
  consignee: string;
  destination_area: null | string;
  destination_city: string;
  consignee_phone: null | string;
  consignee_name: null | string;
  destination_address_line_1: null | string;
  destination_country: string;
  consignee_address: null | string;
  destination_address_line_2: null | string;
  destination_state: string;
  origin_zone: string;
  destination_zone: string;
  service: null | string;
  total_weight: number;
  status: string;
  movable_units: null | string;
  amended_from: null | string;
  company: string;
  cod: number;
  total_cod: number;
  barcode: string;
  branch: null | string;
  currency: string;
  pieces: number;
  not_available: number;
  percentage: number;
  total_fees: number;
  awb_terms_template: null | string;
  awb_terms_and_conditions: null | string;
  sales_invoice_created: number;
  _user_tags: null | string;
  _comments: null | string;
  _assign: null | string;
  _liked_by: null | string;
  geolocation_evkp: null | string;
  shipping_service: string;
  delivery_time: null | string;
  from_client_side: number;
  destination_branch: null | string;
  origin_branch: null | string;
  delivery_due_date: null | string;
  company_currency: string;
  exchange_rate: number;
  overdue: number;
  posting_date: string;
  posting_time: string;
  is_returned: number;
  custodian: null | string;
  assignee: null | string;
  closed: number;
  custodian_commission: number;
  awb_date: string;
  type: null | string;
  origin_address_line_1: null | string;
  service_type: null | string;
  adjusted_cod: number;
}
